### PR TITLE
JBDS-3651 Show a stub first page until angular loads up

### PR DESCRIPTION
**Pull request by jrichter1**
Basically to give the user something to look at while the content is loading. Plus there is a little spinner to show something is happening.

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Please add a JIRA reference to the commit message and PR tittle:
"JBDS-XYZ Show a stub first page until angular loads up."

**Comment by joshuawilson** [comment]
Please update to the latest master branch.

**Comment by ppitonak** [comment]
Can one of the admins verify this patch?

**Comment by jrichter1** [comment]
Closing as outdated.

**Pull request closed without merging**
