### PR TITLE
Update devstudio URL

### PR DESCRIPTION
**Pull request by jrichter1**
Looks like devstudio files got renamed, updating url to compensate

### CODE REVIEW

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
Sooo, the dist task was not in fact prefetching cygwin before packaging the online installer. I shall fix it as well in this PR so the build can pass again.

**Comment by dgolovin** [comment]
Ups, have'n seen this PR, fixed in #319.

**Pull request closed without merging**
