### PR TITLE
JBDS-3669 version the .exe

### PR DESCRIPTION
**Pull request by nickboldt**
JBDS-3669 version the .exe using either the package.json version

### CODE REVIEW

**Comment by nickboldt** [comment]
Rebased. See also https://github.com/redhat-developer-tooling/developer-platform-install/pull/74 for more on parameterizing the output .exe filename. These two changes will need to be carefully merged.

**Comment by ppitonak** [comment]
So with this change, we have this two cases:

1. I can set version in package.json and it will appear inside installer but `npm run package` will produce exe without version or
2. I can run it with `gulp package --version 0.0.2-something` but it will only be part of exe name but won't be visible inside installer

Why don't you just use the version from package.json inside gulpfile to rename exe?

**Comment by nickboldt** [comment]
Simpler PR drops the idea of commandline override. Better?

**Comment by dgolovin** [comment]
Haven't tested it, but it should work IMO.

**Comment by ppitonak** [comment]
Merged.

**Pull request closed without merging**
