### PR TITLE
JBDS-3867 file names should include version match file name on RHCP

### PR DESCRIPTION
**Pull request by dgolovin**

### CODE REVIEW

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
https://github.com/dgolovin/developer-platform-install/blob/443a624bcb0cbe5a19c8b940cf1a77e282821165/requirements-darwin.json#L9 - I think that should say darwin instead of linux

Otherwise the PR looks good.

**Comment by dgolovin** [comment]
That is correct, I was fixing it step by step, but obviously didn't pay to much attention to mac and linux versions. Thanks for review @jrichter1!

**Pull request merged**
