### PR TITLE
Channels UI tabs alignment with components

### PR DESCRIPTION
**Pull request by mohitsuman**
skip ci

### CODE REVIEW

**Comment by mohitsuman** [comment]
screen shot 2017-12-08 at 3 09 11 am

Iteration 1 design.

**Comment by dgolovin** [comment]
Pushed forced update to this branch:
1. Integration with channels.js
2. Added scrolling for tab-content div
3. Fixed visibility for detection in progress (closing div element was missing)

**Comment by jrichter1** [comment]
it looks a bit crammed with the reduced panel width, EAP for example needs an additional row to fit in (not that I knew how to make it look better)

**Comment by mohitsuman** [comment]
@jrichter1 Regarding the above comment for space crunch of component name. I have updated the css and now it will fit into the container box properly. The `detected version` message is migrated at the bottom. 

screen shot 2017-12-12 at 3 10 04 am

**Comment by dgolovin** [comment]
Has it lost scrolling again? There is part of component card visible, but no scrolling.

**Comment by dgolovin** [comment]
scrolling is fine :) 
image

**Pull request merged**
