### PR TITLE
JBDS-4382 Use redirect on dev portal to download kompose 0.6.0

### PR DESCRIPTION
**Pull request by dgolovin**

### CODE REVIEW

**Comment by dgolovin** [comment]
test this

**Comment by jrichter1** [comment]
Guess the redirects are not working

**Comment by dgolovin** [comment]
Yes, they are not available in production yet, but I was able to test them in staging environment.

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Pull request merged**
