### PR TITLE
Update depenencies to latest version

### PR DESCRIPTION
**Pull request by dgolovin**
angular                   1.6.1  →   1.6.2
angular-messages          1.6.1  →   1.6.2
patternfly               3.19.0  →  3.20.0
replace-in-file           2.2.2  →   2.3.2
babel-core               6.22.1  →  6.23.1
babel-preset-node5       12.0.0  →  12.0.1
electron-builder         12.2.2  →  13.9.0
gulp-sourcemaps          ^1.6.0  →  ^2.4.1
mock-fs                  3.12.1  →   4.0.0
protractor                5.1.0  →   5.1.1

### CODE REVIEW

**Comment by jrichter1** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Pull request merged**
