### PR TITLE
Codecov dependency and script added

### PR DESCRIPTION
**Pull request by ppitonak**
See manually imported results in https://codecov.io/gh/redhat-developer-tooling/developer-platform-install. I will update Jenkins jobs after this PR is merged, otherwise it would cause them to fail (non-existing npm script).

### CODE REVIEW

**Comment by ppitonak** [comment]
test this

**Comment by dgolovin** [comment]
@ppitonak is that possible to report coverage for PR on github the same way it is done for almighty-core PR's?

**Comment by dgolovin** [comment]
👍 it looks good

**Comment by ppitonak** [comment]
Thanks for merging. It's configured on Jenkins now so all new PRs will receive a comment from codecov.

**Pull request merged**
