### PR TITLE
JBDS-3657 Installer should set updated default username and password in .cdk

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by fbricon** [comment]
+1 for the change. Not convinced this causes the travis build failure though

**Comment by alexeykazakov** [comment]
This build reports are useless right now. It fails all the time ;)

**Comment by jrichter1** [comment]
The travis builds don't run properly because of github rate limit + jspm + travis only allowing to use a github token for branches in this repo. Builds for PRs from forks just won't work as of now, so don't worry about these. However, that does not mean you shouldn't check it locally :)

**Comment by fbricon** [comment]
Applied in master

**Pull request closed without merging**
