### PR TITLE
Upgrade dependencies to latest

### PR DESCRIPTION
**Pull request by sudhirverma**

### CODE REVIEW

**Comment by sudhirverma** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by sudhirverma** [comment]
test this

**Comment by jrichter1** [comment]
mocha 3.5.2 seems to contain a bug in xunit reporter, please try with 3.5.3

**Comment by sudhirverma** [comment]
Thanks :) @jrichter1

**Pull request merged**
