### PR TITLE
JBDS-4370 Windows uninstaller is not deleting "uninstaller" and "temp" and parent folders

### PR DESCRIPTION
**Pull request by sudhirverma**

### CODE REVIEW

**Comment by sudhirverma** [comment]
I don't think if folder is open it will lock the process (it will lock the process if files are open).

'Get-ChildItem $folder\.. -Recurse | Remove-Item -Force' it will remove all the file and folder even if that folder is open.

**Comment by jrichter1** [comment]
Did you try to just navigate to the uninstaller folder and run the script from context menu (run with powershell) ? Because I did, and the folder still wasn't deleted afterwards.

**Comment by jrichter1** [comment]
Alright, neither seems to work for me, it still complains the $installFolder\uninstaller is in use by another process.

**Comment by sudhirverma** [comment]
If you run from cmd promt it work fine 'powershell.exe -File '.\uninstall'

**Comment by jrichter1** [comment]
You could have run it from CLI before (not sure if there was a limitation on the folder it was run from). But that is not what the linked issue is about, is it?

**Comment by sudhirverma** [comment]
issue says right click and run with powershell, uninstall all the component, delete parent and subfolder,
by running 'Get-ChildItem $folder.. -Recurse | Remove-Item -Force' in powershell CLI it works fine
and when I  right click and run with powershell it shows me 'it is being used by another process'

**Comment by jrichter1** [comment]
I'm not saying there is something wrong with this change, it just doesn't seem to fix what it set out to. I mean, I can merge it simply because your code looks cleaner and gets rid of some unused stuff.

So the question is: Do you want to try and tackle the explorer "run with" issue now, or do you want to get this code in and leave the rest to later?

**Comment by sudhirverma** [comment]
I am working on this to resolve the issue.

**Comment by sudhirverma** [comment]
test this

**Comment by jrichter1** [comment]
Works for me

**Pull request merged**
