### PR TITLE
JBDS-3926 cache build tools

### PR DESCRIPTION
**Pull request by jrichter1**
Replacement for #211 - with tools being downloaded to a separate folder to avoid them being bundled into the final archive.

### CODE REVIEW

**Comment by jrichter1** [comment]
Aaand the latest symlink is gone from devstudio updatesite :/

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
test this

**Comment by nickboldt** [comment]
Do you mean https://devstudio.jboss.com/10.0/snapshots/builds/devstudio.product_master/latest/all/repo/ or https://devstudio.jboss.com/10.0/snapshots/updates/ ? Both work for me.

**Comment by dgolovin** [comment]
Released to master after re-base as  3fd7386.

**Pull request closed without merging**
