### PR TITLE
JBDS-3909 refactoring

### PR DESCRIPTION
**Pull request by dgolovin**
Red Hat Developer Studio -> Red Hat JBoss Developer Studio;
Developer Platform -> Development Suite

### CODE REVIEW

**Comment by dgolovin** [comment]
@ppitonak could you check why UI tests failed in CI? Everything is fine in local build.

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
It looks like something broke on the slave - our resident expert is looking into it

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
nvm/node wrestled into submisson - build is green again

**Comment by ppitonak** [comment]
thanks @jrichter1

**Comment by dgolovin** [comment]
If everything is fine I am going to push it after I got updated image for installer title.

**Comment by dgolovin** [comment]
Title is updated to 'Development Suite' waiting for checks to pass

**Pull request merged**
