### PR TITLE
Gulp task package refactored into multiple tasks

### PR DESCRIPTION
**Pull request by ppitonak**

### CODE REVIEW

**Comment by ppitonak** [comment]
@dgolovin, @jrichter1 please review and merge if everything is OK.

**Comment by ppitonak** [comment]
Rebased

**Comment by ppitonak** [comment]
Updated and rebased

**Comment by jrichter1** [comment]
I'm getting the following error from 'unzip-7zip-extra' when running a package task.

 Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\Users\jbossqa\Downloads\developer-platform-install\dist\win\7za.exe e C:\Users\jbossqa\Downloads\developer-platform-install\dist\win\7z920_extra.7z -oC:\Users\jbossqa\Downloads\developer-platform-install\dist\win -y 7zS.sfx"
'C:\Users\jbossqa\Downloads\developer-platform-install\dist\win\7za.exe' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[12:37:24] Error in plugin 'run-sequence'
Message:
    An error occured in task 'unzip-7zip-extra'.

**Comment by ppitonak** [comment]
Fixed

**Comment by jrichter1** [comment]
A wild error has appeared:

Creating C:\Users\jbossqa\Downloads\developer-platform-install\dist\win\DeveloperPlatformInstaller-win32-x64-0.0.2.exe
[13:09:17] 'package' errored after 347 μs
[13:09:17] ReferenceError: cmd is not defined
    at Gulp.<anonymous> (C:\Users\jbossqa\Downloads\developer-platform-install\gulpfile.js:120:8)

**Comment by ppitonak** [comment]
Fixed

**Comment by jrichter1** [comment]
Pushed to master.

**Pull request closed without merging**
