### PR TITLE
Channels navbar UI enhancement

### LINKED ISSUE #1165: Channels UI navigation enhancement
Make the enhancement for vertical navigation bar -> channels UI.
This will be in sync with UX review.

### PR DESCRIPTION
**Pull request by mohitsuman**
Fix #1165 
Making the changes for the vertical navbar in channels UI.

screen shot 2017-12-20 at 2 09 44 am

### CODE REVIEW

**Comment by mohitsuman** [comment]
@dgolovin One more template, I can add for the navbar looks like this. I will discuss this too with UX and get their view based on the 2 designs.

screen shot 2017-12-20 at 4 57 40 pm

**Comment by dgolovin** [comment]
I am not UX, but what if channel selection would be be same color as button?

**Comment by dgolovin** [comment]
Or it pick darker blue from Pantone 306 in accent colors on https://brand.redhat.com/elements/color/.

**Comment by dgolovin** [comment]
How would (selected out of totalnumber) would fit into it?

**Comment by mohitsuman** [comment]
After discussion with UX, we have decided to remove the red color as it making it more overwhelming on the entire page. I have made it in sync with the light tone and Blue color pallete as used across Red Hat products currently.

screen shot 2017-12-20 at 8 11 48 pm

**Comment by mohitsuman** [comment]
@dgolovin For the `selected out of totalnumber `, I will share the screenshot.

**Comment by mohitsuman** [comment]
As per reviews with UX and add select all buttons inside the channel view, I have made the css changes. The nav bars colors are in accordance with the brand colors suggested.

screen shot 2018-01-01 at 7 37 39 pm

**Comment by mohitsuman** [comment]
test this

**Comment by mohitsuman** [comment]
test this

**Comment by mohitsuman** [comment]
test this

**Comment by mohitsuman** [comment]
Layout with component count badge in a given channel.

screen shot 2018-01-02 at 6 57 12 pm

**Comment by mohitsuman** [comment]
test this

**Comment by mohitsuman** [comment]
test this

**Comment by mohitsuman** [comment]
test this

**Pull request merged**
