### PR TITLE
JBDS-3803 Add JavaVM version detection and validation

### PR DESCRIPTION
**Pull request by dgolovin**

### CODE REVIEW

**Comment by dgolovin** [comment]
@jrichter1 could you try it out before I push it?  It is not part of BOM but a feature that is good to have.

**Comment by jrichter1** [comment]
Will do.

**Comment by jrichter1** [comment]
It seems unlike vagrant and virtualbox, java can be selected to install even if detected. Is that intended?

**Comment by dgolovin** [comment]
That is correct, because OpenJDK is still delivered as a zip file, so we I unpack it  and then use in DevStudio installation without any conflicts with detected java.

**Comment by jrichter1** [comment]
Good, I'm going to try some install combinations after my bundled build has finished downloading (which is probably going to take a while, sorry)

**Comment by dgolovin** [comment]
Also notice if detected version is used there would be no progress on install page for openjdk, for vagrant and virtual box would be shown even if they are detected. It mostly because vagrant is always vagrant detected or installed. there are several reasons for different behavior here:
- vagrant detected or installed is still vagrant, where instead of OpenJDK we can use detected Oracle JDK;
- even if vagrant detected we still do environment configuration for it.

**Comment by jrichter1** [comment]
Deselecting components causes an uncaught error when I click 'download and install' and everything basically falls apart. I'm using the build generated by the PR builder.

fail

**Comment by dgolovin** [comment]
PR build might be the problem here. Could you take a look at https://issues.jboss.org/browse/JBDS-3787 using CI build form machydra?

**Comment by jrichter1** [comment]
OK, the last commit is the cause. Builds up to 174 work, the newest doesn't.

**Comment by dgolovin** [comment]
You right, that is an issue, with last change. I'll send PR with fix after I replicate it locally. 
Thanks Jan!

**Comment by dgolovin** [comment]
https://github.com/redhat-developer-tooling/developer-platform-install/pull/219 to fix the issue. Problem is current UI is intermediate version on the way to original design with radio buttons. Current implementation with check boxes is using 'install' option value to indicate install is requested and 'detected' when install is skipped. 'detected' option is added to list of options only in case installer found already installed components, so code should check if 'detected' option is present before using it.

**Comment by dgolovin** [comment]
https://github.com/redhat-developer-tooling/developer-platform-install/pull/219 is released to master

**Pull request merged**
