### PR TITLE
JBDS-3769, JBDS-3958: JSPM removed, Babel runs at build time

### PR DESCRIPTION
**Pull request by jrichter1**
- JSPM has been removed (at last)
 - Babel updated
 - The entire project is now transpiled using Babel before 'generate'/'run' tasks saving loading time at the start of the app
 - *.es6.js files renamed to *.js since they are no longer transpiled on their own
 - Transpiled sources are put into a new folder, hence model classes needed an update to their bundled files paths

### CODE REVIEW

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
Sourceforge seems to be down, can't download 7zip and finish the build...

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
It works good. The only problem is at development time only transpiled scripts are present and makes debugging difficult.

**Comment by jrichter1** [comment]
I've added sourcemaps to the transpiled scripts, so the original ones should now be visible in the debugger under 'sources'.

**Comment by dgolovin** [comment]
That works, thanks!

**Pull request merged**
