### PR TITLE
JBDS-3889 Remove JBoss from Platform Installer full name

### PR DESCRIPTION
**Pull request by dgolovin**
Fix updates name to 'Red Hat Developer Studio PLatform Installer'

### CODE REVIEW

**Comment by dgolovin** [comment]
npm install fails with error "Error: Cannot find module 'electron'" on CI host local build works fine

**Comment by jrichter1** [comment]
Something interrupted the electron-prebuild download so the unit tests failed. As for the UI tests the path is currently hardcoded in the protractor config and I assume it needs adjusting. Could you do that as well?

**Comment by dgolovin** [comment]
@jrichter1 thanks for pointing that out :) haven't run ui-tests.

**Comment by dgolovin** [comment]
pr updated and all checks are good.

**Pull request merged**
