### PR TITLE
JBDS-3666 Back off and retry if download fails

### PR DESCRIPTION
**Pull request by dgolovin**
Fix enables:
- downloader to save failed downloads
- instll step restart download from dialog

### CODE REVIEW

**Comment by jrichter1** [comment]
The ui test job does not look very stable yet. I can see no changes that would break it here, so let me launch it again and see what it does.

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
Soo, the failure detection works for all the components, but the restart is only implemented for CDK, correct? That's going to throw errors any time something else fails to download and restart is clicked. Plus the VPN message is sort of CDK specific and hopefully only temporary.

**Comment by dgolovin** [comment]
Yep, that was correct :) now it is fixed.

**Comment by dgolovin** [comment]
Ouch, I tests were failing when request.defaults() used, fixed that and returned initial route to account in main.js.

**Pull request merged**
