### PR TITLE
move prefetched requirements to a new folder...

### PR DESCRIPTION
**Pull request by nickboldt**
move prefetched requirements to a new folder so they can be reused between builds

### CODE REVIEW

**Comment by ppitonak** [comment]
- [x] `npm run package-simple` works fine
- [ ] `npm run package-bundle` with no prefetch deps downloads all deps and generates *36MB installer*
- [ ] `echo 'aaa' >> prefetch-dependencies/cdk.zip && npm run package-bundle` correctly detected that file is corrupt and started downloding it again, Gulp task _prefetch_ failed because of "task completion callback called too many times"
- [ ] `npm run dist` - didn't run this

**Comment by nickboldt** [comment]
Yeah, I know about "task completion callback called too many times" but not sure how to fix. Will squash if someone can suggest how to fix the callback problem.

**Comment by ppitonak** [comment]
BTW, it would be nicer to implement prefetch task using Promise.all (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)

**Comment by dgolovin** [comment]
@ppitonak @nickboldt +1 for using Promise.all

**Comment by nickboldt** [comment]
replaced by #158

**Pull request closed without merging**
