### PR TITLE
Update devstudio URLs

### PR DESCRIPTION
**Pull request by jrichter1**
Build is failing on devstudio link returning 404, updating the appropriate URLs so we can build again.

### CODE REVIEW

**Comment by jrichter1** [comment]
@dgolovin @ppitonak care for a review?

**Comment by dgolovin** [comment]
I think we should use link to latest build, not specific one, because it is going to be deleted at some point.

**Comment by jrichter1** [comment]
It's the same staged build as before, just the file name changed for some reason, so it probably won't get deleted any time soon.
But if you wish, I'll update it to the latest build - as long as our builds get fixed I'm fine with it.

**Comment by dgolovin** [comment]
I created new one https://github.com/redhat-developer-tooling/developer-platform-install/pull/237

**Comment by jrichter1** [comment]
Well then

**Pull request closed without merging**
