### PR TITLE
Update dependencies to latest

### PR DESCRIPTION
**Pull request by dgolovin**

### CODE REVIEW

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
Surprisingly unit tests are fine under Windows 10.

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
Right, the majority of failures were caused by a missing dependency in package-lock.json. I'm guessing the transitive dependencies differ between platforms, so having the package-lock file is probably going to cause problems. Anyhow, I've set the CI to ignore the file and just do a fresh npm install.

Now there are 3 failed tests, which will need some updating.

**Comment by dgolovin** [comment]
test this

**Pull request merged**
