### PR TITLE
Additional detection indicator tweaks

### PR DESCRIPTION
**Pull request by jrichter1**
I've tried to meddle with #685 a little
 - split the detection indicator and the status message
 - slapped the indicator on top of the form, because otherwise it would look too transparent

@sudhirverma WDYT?

### CODE REVIEW

**Comment by sudhirverma** [comment]
@jrichter1 LGTM :+1:

**Comment by dgolovin** [comment]
@jrichter1 here is the PR for that https://github.com/jrichter1/developer-platform-install/pull/1

**Comment by jrichter1** [comment]
@dgolovin thanks for the PR for this humble PR, I've merged it

**Comment by jrichter1** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
replaced with new PR https://github.com/redhat-developer-tooling/developer-platform-install/pull/686 that put opacity to 95%.

**Pull request closed without merging**
