### PR TITLE
JBDS-4423 Refactor Installer services: dependencies resolution and installation ordering

### PR DESCRIPTION
**Pull request by dgolovin**
This fix includes prep changes required for Fuse Tools Installer:
* moves installer ordering configuration from code to
requirements.json file;
* introduce additional parameter for devstudio installer to allow fuse
installer to provide correct key value;
* introduces additional parameters to list additional IUs to install;
* swithces to factory metod fromJason to create installer instances;
* add 'requires' attributes to installer's configuration, but those are
not used yet on confirmation page.

### CODE REVIEW

**Comment by jrichter1** [comment]
I've found an issue with component detection: Detected components that can be reinstalled (jdk, cygwin on windows) don't immediately show up as detected. They do show up as detected when they are deselected.

**Comment by dgolovin** [comment]
Thanks @jrichter1! I'll check what is going on.

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
test this

**Pull request merged**
