### PR TITLE
Make progress bars useful again

### PR DESCRIPTION
**Pull request by jrichter1**
An attempt to make the progress bars more friendly than they appear to be now:
 - determinate progress only for downloads, now includes downloaded / total sizes
 - waiting and installing switches to animated indeterminate progress
 - failed components' progress bar turns red
 - completed progress bar turns green
 - restarting downloads resets the downloading progress

Comments, criticism, issues, etc. welcome

### CODE REVIEW

**Comment by jrichter1** [comment]
progress

**Comment by dgolovin** [comment]
Does it handle re-download of one file from CDK? It seems just reset counters to 0, but it should decrease downloaded by actual amount downloaded before failure.

What if progress is shown only for setup, when vagrant and virtualbox were detected?

**Comment by dgolovin** [comment]
From design point of view I think we should keep it as close as possible to document attached here https://patternfly.atlassian.net/browse/RHUAP-26. There is no colored progress bars in design UX team suggested.

**Comment by dgolovin** [comment]
Could you separate progress for download,  waiting/installing switches to animated indeterminate progress and coloring failed/completed progress and submit them as separated PR's?

**Comment by jrichter1** [comment]
A quick answer compilation:
 - restarting doesn't work on a per file basis - will definitely look into that
 - setup bars look the same as installation ones
 - colouring can be omitted / separated from the rest no problem
 - splitting download/wait/install etc. could make a mess of things

**Comment by jrichter1** [comment]
Fixed up the damn error - now it should correctly add up the download size for multiple files, plus restarting download now works properly if some file already finished downloading.

Also removed the colouring for now, so it's all blue (downloading, finished) or striped blue (waiting, installing, setting up).

**Comment by dgolovin** [comment]
That is awesome! Thanks! Just in time for next PR with download-manager links for testing.
Released to master as  707a1e2 after re-base.

**Pull request closed without merging**
