### PR TITLE
Promisify JBDS installer and test it

### PR DESCRIPTION
**Pull request by jrichter1**

### CODE REVIEW

**Comment by dgolovin** [comment]
After applying this PR tests are failing for me:
``` javascript
  84 passing (756ms)
  12 failing

  1) Downloader download "after each" hook:
     Uncaught Error: EBADF: bad file descriptor, write
      at Error (native)

  2) Installer "before all" hook:
     Uncaught Error: EBADF, bad file descriptor
      at Binding._getDescriptorById (node_modules/mock-fs/lib/binding.js:187:11)
      at Binding.<anonymous> (node_modules/mock-fs/lib/binding.js:373:27)
      at maybeCallback (node_modules/mock-fs/lib/binding.js:27:18)
      at Binding.writeBuffer (node_modules/mock-fs/lib/binding.js:372:10)
      at Object.fs.write (node_modules/mock-fs/node/fs-4.0.0.js:563:20)
      at WriteStream._write (node_modules/mock-fs/node/fs-4.0.0.js:1773:6)
      at doWrite (_stream_writable.js:292:12)
      at writeOrBuffer (_stream_writable.js:278:5)
      at WriteStream.Writable.write (_stream_writable.js:207:11)
      at Request.ondata (stream.js:31:26)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:959:12)
      at readableAddChunk (_stream_readable.js:146:16)
      at IncomingMessage.Readable.push (_stream_readable.js:110:10)
      at HTTPParser.parserOnBody (_http_common.js:109:22)
      at TLSSocket.socketOnData (_http_client.js:305:20)
      at readableAddChunk (_stream_readable.js:146:16)
      at TLSSocket.Readable.push (_stream_readable.js:110:10)
      at TLSWrap.onread (net.js:523:20)

  3) Downloader download should call errorHandler when error event is emitted:
     TypeError: Attempted to wrap get which is already wrapped
      at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core.js:81:29)
      at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:121:21)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
      at Context.<anonymous> (test/unit/model/helpers/downloader-test.js:86:13)
  --------------
  Error: Stack Trace for original
      at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:140:34)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
      at Context.<anonymous> (test/unit/model/helpers/downloader-test.js:86:13)

  4) Installer execFile should reject when an error occurs:
     TypeError: Attempted to wrap execFile which is already wrapped
      at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core.js:81:29)
      at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:121:21)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
      at Context.<anonymous> (test/unit/model/helpers/installer-test.js:118:24)
  --------------
  Error: Stack Trace for original
      at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:140:34)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
      at Context.<anonymous> (test/unit/model/helpers/installer-test.js:118:24)

  5) Installer exec should reject when an error occurs:
     TypeError: Attempted to wrap exec which is already wrapped
      at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core.js:81:29)
      at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:121:21)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
      at Context.<anonymous> (test/unit/model/helpers/installer-test.js:77:24)
  --------------
  Error: Stack Trace for original
      at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:140:34)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
      at Context.<anonymous> (test/unit/model/helpers/installer-test.js:77:24)

  6) Login controller initial state username should be empty:
     TypeError: Cannot read property 'username' of undefined
      at Context.<anonymous> (test/unit/pages/account/controller-test.js:26:24)

  7) Login controller initial state password should be empty:
     TypeError: Cannot read property 'password' of undefined
      at Context.<anonymous> (test/unit/pages/account/controller-test.js:31:24)

  8) Login controller initial state terms and conditions should be considered signed:
     TypeError: Cannot read property 'tandcNotSigned' of undefined
      at Context.<anonymous> (test/unit/pages/account/controller-test.js:36:24)

  9) Login controller initial state terms and conditions should be considered signed:
     TypeError: Cannot read property 'tandcNotSigned' of undefined
      at Context.<anonymous> (test/unit/pages/account/controller-test.js:36:24)

  10) Login controller login should make an HTTP request:
     TypeError: Cannot read property 'encode' of undefined
      at AccountController.login (browser/pages/account/controller.js:26:48)
      at Context.<anonymous> (test/unit/pages/account/controller-test.js:53:18)

  11) Login controller login should make an HTTP request:
     TypeError: Cannot read property 'encode' of undefined
      at AccountController.login (browser/pages/account/controller.js:26:48)
      at Context.<anonymous> (test/unit/pages/account/controller-test.js:53:18)

  12) Login controller login should make an HTTP request:
     TypeError: Cannot read property 'encode' of undefined
      at AccountController.login (browser/pages/account/controller.js:26:48)
      at Context.<anonymous> (test/unit/pages/account/controller-test.js:53:18)
```

**Comment by dgolovin** [comment]
verified and released to master.

**Comment by jrichter1** [comment]
Uhm, is it failing miserably or was it some kind of a hiccup? Anyway, I'm reopening this, since it definitely is not released to master and I'm not even sure if it is verified. Apparently, there's been some error in the workflow. Can you recheck?

**Comment by jrichter1** [comment]
Tests should no longer run into such unexpected problems now. @dgolovin, can you try once more?

**Comment by dgolovin** [comment]
it worked. Released to master.

**Pull request merged**
