### PR TITLE
Extend system tests

### PR DESCRIPTION
**Pull request by jrichter1**
- add tests for user defined target folder
 - add tests for component detection
 - scripts for CI updated
 - add some ids to elements for lookup

### CODE REVIEW

**Comment by dgolovin** [comment]
@jrichter1 we need to put CI shell scripts in SCM as well or even whole jenkins configuration. It would be probably private repository or internal gitlab instance. Otherwise changes to CI are not visible.
WDYT?

**Comment by jrichter1** [comment]
@dgolovin I don't really mind either way. 
As far as the scripts go, they can still be used as a convenience method to run the tests, so there is no harm to have them here. They don't contain anything internal.
But I agree about the configuration, we should probably store it somewhere. Do you happen to have a nice repo ready for such a thing?

**Comment by dgolovin** [comment]
Nope, I have nothing ready for this. I know devstudio has private repo for this on github, but I would use gitlab instance.

**Comment by dgolovin** [comment]
@jrichter1 I am +1 to release it to master.  We'll take care of CI shell scripts sharing later.

**Comment by jrichter1** [comment]
Very well, I shall get to it once I figure out what the hell I was doing before holidays kicked in :)

**Comment by jrichter1** [comment]
Released to master as 62f2940.

**Pull request closed without merging**
