### PR TITLE
Coverage report for unit-tests with istanbul

### PR DESCRIPTION
**Pull request by dgolovin**
Simple version of https://github.com/ppitonak/developer-platform-install/tree/jspm_removed2

### CODE REVIEW

**Comment by dgolovin** [comment]
test this

**Comment by jrichter1** [comment]
Could you also add the 'coverage' folder into gitignore? For convenience.

**Comment by dgolovin** [comment]
I've added coverage to .gitignore.

**Comment by dgolovin** [comment]
released after rebase as commit cc4600ce2f01dd0758c934d04eaa7e6f471005a2

**Pull request closed without merging**
