### PR TITLE
JBDS-4411: Add install size field at footer

### PR DESCRIPTION
**Pull request by mohitsuman**
Positioned the Install size field at the footer. This basically checks the total install size based on the selection of the components by the user. 
https://issues.jboss.org/browse/JBDS-4411

### CODE REVIEW

**Comment by mohitsuman** [comment]
test this

**Comment by mohitsuman** [comment]
test this

**Comment by dgolovin** [comment]
total disk space should be calculated as sum of two: resources required to download, disk space required to install

**Comment by mohitsuman** [comment]
@dgolovin the install size field will be handy to get the disk space required field. How are we targeting to calculate the resources required to download.

**Comment by dgolovin** [comment]
Replaced with https://github.com/redhat-developer-tooling/developer-platform-install/pull/872.

**Pull request closed without merging**
