### PR TITLE
JBDS-3997 Upgrade to vagrant 1.8.1 and compatible virtual box 5.0.26

### PR DESCRIPTION
**Pull request by dgolovin**

### CODE REVIEW

**Comment by dgolovin** [comment]
test this

**Comment by dgolovin** [comment]
Should also adjust validation to new version.

**Comment by jrichter1** [comment]
Test failures aside, are we getting rid of the developers.redhat.com redirects?

**Comment by dgolovin** [comment]
I am temporary put direct links and created for redirects I'll create issues in RHDENG and then update them when they are in place.

**Comment by dgolovin** [comment]
Released to master as 9dff7ee after re-base.

**Pull request closed without merging**
